### PR TITLE
add xpath book search tool

### PR DESCRIPTION
**Pull request by kerwinso**
Add the tool that Cade coded this summer (https://github.com/caderitter/xpath-book-search), and update the cnx-tools readme accordingly.

### CODE REVIEW

**Comment by philschatz** [comment]
I think this now being done directly in https://github.com/Connexions/cnx-archive/pull/506 so no need for a separate script that has access to the DB. 

@kerwinso : can this Pull Request be closed when that code is merged?

**Comment by kerwinso** [comment]
@philschatz Yes, on the following conditions:

1) @brittweinstein and myself fully understand how to use the xpath extension with examples (I guess in Cade's absence, you would be the point person on this). 
We'd already sat down with Cade a couple times on this script and hammered out the documentation (which is part of this PR)... but I like the idea of using something that would actually be supported going forward.

2) The xpath extension would have to meet the same user requirements as this script.

**Comment by kerwinso** [comment]
@philschatz Per @karenc, https://github.com/Connexions/cnx-archive/pull/506 requires a book uuid to work. As such, it is not sufficient for my or @brittweinstein /CM's needs, because the goal is to find matching content inside collections whose uuid's we _don't_ know. Also, 506 was developed without product owner or stakeholder input (Britt) and without the original developer (Cade), and there is very little documentation. It may be fixed eventually but we have a lot of other priorities in the meantime.

Therefore, @edwoodward please merge this Pull Request, as we still need this xpath book search tool.

**Comment by philschatz** [comment]
@kerwinso have your conditions been met (can this PR be closed or merged)?

**Comment by kerwinso** [comment]
@philschatz I'm going to merge this PR, just so that this tool has _someplace_ to live within our organization repos (it doesn't affect any other code). IIRC, it is usable in its current state as a standalone separate tool to query the db.

Six plus months ago, we got off on a tangent about having the same functionality as this tool in our cnx-archive API instead. Reading back through the various PR/issue comments, it sounds like the first attempt in https://github.com/Connexions/cnx-archive/pull/506 was a bust -- at least from a CM/QA perspective. 

And it looks like subsequent discussions to improve the API again started happening in https://github.com/Connexions/cnx-archive/issues/533 -- but that's still floating out there in the "someday we'll get to it" ether.

**Pull request merged**
